services:
    - postgres:17

variables:
  POSTGRES_DB: lambda_search
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: root

stages:
  - lint
  - test

pep8_check:
  stage: lint
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - flake8 --verbose .

black_check:
  stage: lint
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check .

django-tests:
  stage: test
  image: python:3.12
  script:
    - export DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB
    - apt-get update -qy
    - pip install -r requirements/test.txt
    - python3 manage.py makemigrations
    - python3 manage.py migrate
    - python3 manage.py test