default:
   services:
     - postgres:17

variables:
  DJANGO_POSTGRESQL_NAME: $POSTGRES_DB
  DJANGO_POSTGRESQL_USER: $POSTGRES_USER
  DJANGO_POSTGRESQL_PASSWORD: $POSTGRES_PASSWORD
  DJANGO_POSTGRESQL_HOST: localhost
  DJANGO_POSTGRESQL_PORT: 5432

stages:
  - lint
  - test

pep8_check:
  stage: lint
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - flake8 --verbose .

black_check:
  stage: lint
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check .

django-tests:
  stage: test
  image: python:3.11
  script:
    - pip install -r requirements/test.txt
    - cd lambda_search
    - python manage.py test