stages:
  - lint
  - test

pep8_check:
  stage: lint
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - flake8 --verbose .

black_check:
  stage: lint
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check .

django-tests:
  stage: test
  image: python:3.11
  script:
    - pip install -r requirements/test.txt
    - cd lambda_search
    - python manage.py test