services:
    - postgres:17

variables:
  POSTGRES_DB: lambda_search
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: root

stages:
  - lint
  - test

pep8_check:
  stage: lint
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - flake8 --verbose .

black_check:
  stage: lint
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check .

django-tests:
  stage: test
  image: python:3.12
  env:
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
  script:
    - export DATABASE_URL=postgres://root:@postgres:5432/lambda_search
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r requirements/test.txt
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py test Project