name: "lambda_search"

services:
  postgres_lambda:
    image: postgres:17
    container_name: postgres_lambda
    environment:
      POSTGRES_DB: ${DJANGO_POSTGRESQL_NAME}
      POSTGRES_USER: ${DJANGO_POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${DJANGO_POSTGRESQL_PASSWORD}
    restart: always
    volumes:
      - ./for_docker/postgres_data:/var/lib/postgresql/data
    profiles:
      - prod
      - dev
    networks:
      - lambda_net

  django:
    build: .
    container_name: django
    env_file:
      - ./.env
    restart: always
    volumes:
      - ./for_docker/static:/lambda_search/static
      - ./for_docker/media:/lambda_search/media
      - ./for_docker/logs/django:/lambda_search/logs
    depends_on:
      - postgres_lambda
    profiles:
      - prod
      - dev
    networks:
      - lambda_net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
        tag: "django"

  redis:
    image: redis:7-alpine
    container_name: redis_lambda
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - ./for_docker/redis_data:/data
      - ./for_docker/redis_conf:/usr/local/etc/redis
    profiles:
      - prod
      - dev
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - lambda_net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
        tag: "redis"

  celery:
    build: .
    container_name: celery_lambda
    command: celery -A lambda_search worker --pool=solo --loglevel=DEBUG --logfile=/lambda_search/logs/celery.log
    env_file:
      - ./.env
    restart: always
    volumes:
      - ./for_docker/logs/celery:/lambda_search/logs
      - ./for_docker/media:/lambda_search/media
    depends_on:
      - redis
      - postgres_lambda
    profiles:
      - prod
      - dev
    networks:
      - lambda_net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
        tag: "celery"

  nginx-prod:
    image: jonasal/nginx-certbot:latest
    container_name: nginx-prod
    environment:
      - DEBUG=${LAMBDA_CERTBOT_DEBUG}
      - STAGING=${LAMBDA_CERTBOT_STAGING}
      - CERTBOT_EMAIL=${LAMBDA_CERTBOT_EMAIL}
      - NGINX_MAX_BODY_SIZE=10G
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./for_docker/nginx-confs/lambda_search_prod.conf:/etc/nginx/user_conf.d/lambda_search.conf
      - ./for_docker/nginx_certificates:/etc/letsencrypt
      - ./for_docker/static:/lambda_search/static
      - ./for_docker/media:/lambda_search/media
      - ./for_docker/logs/nginx:/var/log/nginx
    depends_on:
      - django
    profiles:
      - prod
    networks:
      - lambda_net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
        tag: "nginx-prod"

  nginx-dev:
    image: nginx:latest
    container_name: nginx-dev
    environment:
      - NGINX_MAX_BODY_SIZE=10G
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./for_docker/nginx-confs/lambda_search_dev.conf:/etc/nginx/conf.d/default.conf
      - ./for_docker/static:/lambda_search/static
      - ./for_docker/media:/lambda_search/media
      - ./for_docker/logs/nginx:/var/log/nginx
    depends_on:
      - django
    profiles:
      - dev
    networks:
      - lambda_net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
        tag: "nginx-dev"

networks:
  lambda_net:
    name: lambda_search
    driver: bridge

