# Generated by Django 4.2.16 on 2024-12-18 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import feedback.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(max_length=100, verbose_name="Текст"),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Создано в"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "получено"),
                            ("processing", "в обработке"),
                            ("answered", "ответ дан"),
                        ],
                        default="received",
                        max_length=20,
                        verbose_name="Статус обработки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Обратная связь",
                "verbose_name_plural": "Обратные связи",
            },
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Имя",
                    ),
                ),
                (
                    "mail",
                    models.EmailField(max_length=254, verbose_name="Почта"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_info",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userinfo",
                        to="feedback.feedback",
                        verbose_name="Информация о пользователе",
                    ),
                ),
            ],
            options={
                "verbose_name": "Информация о пользователе",
                "verbose_name_plural": "Информация о пользователях",
            },
        ),
        migrations.CreateModel(
            name="StatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Создано в"
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("received", "получено"),
                            ("processing", "в обработке"),
                            ("answered", "ответ дан"),
                        ],
                        db_column="from",
                        max_length=20,
                        verbose_name="Из",
                    ),
                ),
                (
                    "to",
                    models.CharField(
                        choices=[
                            ("received", "получено"),
                            ("processing", "в обработке"),
                            ("answered", "ответ дан"),
                        ],
                        db_column="to",
                        max_length=20,
                        verbose_name="В",
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="feedback.feedback",
                        verbose_name="Обратная связь",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог изменения статуса",
                "verbose_name_plural": "Логи изменения статусов",
            },
        ),
        migrations.CreateModel(
            name="FeedbackFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=feedback.models.FeedbackFile.upload_to_path,
                        verbose_name="файл",
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="feedback.feedback",
                        verbose_name="Обратная связь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Файл обратной связи",
                "verbose_name_plural": "Файлы обратной связи",
            },
        ),
        migrations.AddField(
            model_name="feedback",
            name="author",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="feedback.userinfo",
            ),
        ),
    ]
