# Generated by Django 4.2.16 on 2025-03-21 18:33

from django.db import migrations, models
import feedback.models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackfile",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=feedback.models.FeedbackFile.upload_to_path,
                verbose_name="файл",
            ),
        ),
    ]
