# Generated by Django 4.2.16 on 2025-06-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_alter_feedbackfile_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="text",
            field=models.CharField(max_length=500, verbose_name="Текст"),
        ),
    ]
