# Generated by Django 4.2.16 on 2025-06-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0003_alter_feedback_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="text",
            field=models.CharField(max_length=1000, verbose_name="Текст"),
        ),
    ]
