# Generated by Django 4.2.16 on 2024-12-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QueryHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "query",
                    models.CharField(max_length=255, verbose_name="Запрос"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата запроса"
                    ),
                ),
                (
                    "database",
                    models.CharField(
                        max_length=255, verbose_name="База данных"
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        help_text="Результаты поиска в формате JSON",
                        verbose_name="Результаты",
                    ),
                ),
            ],
            options={
                "verbose_name": "История запроса",
                "verbose_name_plural": "История запросов",
            },
        ),
    ]
