# Generated by Django 4.2.16 on 2024-12-10 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("history", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="queryhistory",
            name="user",
            field=models.ForeignKey(
                default=4,
                help_text="Пользователь, которому принадлежит эта история",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="query_histories",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
            preserve_default=False,
        ),
    ]
