# Generated by Django 4.2.16 on 2024-12-16 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0002_queryhistory_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="queryhistory",
            name="database",
        ),
    ]
