# Generated by Django 4.2.16 on 2024-12-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ManagedDatabase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Имя базы данных",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="Путь к файлу базы данных SQLite",
                        max_length=500,
                        verbose_name="Путь к базе данных",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Определяет, используется ли эта база данных",
                        verbose_name="Активна",
                    ),
                ),
            ],
            options={
                "verbose_name": "База данных",
                "verbose_name_plural": "Базы данных",
            },
        ),
    ]
