# Generated by Django 4.2.16 on 2024-12-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0002_remove_manageddatabase_path_manageddatabase_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="manageddatabase",
            name="history",
            field=models.TextField(
                default="", max_length=500, verbose_name="История"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="manageddatabase",
            name="active",
            field=models.BooleanField(
                default=False,
                help_text="Определяет, используется ли эта база данных",
                verbose_name="Активна",
            ),
        ),
    ]
