# Generated by Django 4.2.16 on 2025-03-26 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0003_manageddatabase_progress_task_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manageddatabase",
            name="progress_task_id",
        ),
    ]
