# Generated by Django 4.2.16 on 2025-03-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0005_manageddatabase_progress_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="manageddatabase",
            name="encryption_started",
            field=models.BooleanField(
                default=False, verbose_name="шифрование запущено"
            ),
        ),
    ]
