# Generated by Django 4.2.16 on 2024-12-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0005_alter_manageddatabase_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="manageddatabase",
            name="is_encrypted",
            field=models.BooleanField(
                default=False, verbose_name="Зашифрована"
            ),
        ),
    ]
