# Generated by Django 4.2.16 on 2024-12-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0006_manageddatabase_is_encrypted"),
    ]

    operations = [
        migrations.AddField(
            model_name="manageddatabase",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AddField(
            model_name="manageddatabase",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Дата обновления"
            ),
        ),
        migrations.AlterField(
            model_name="manageddatabase",
            name="is_encrypted",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Зашифрована"
            ),
        ),
    ]
