# Generated by Django 4.2.16 on 2024-12-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0007_manageddatabase_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manageddatabase",
            name="history",
            field=models.TextField(
                blank=True,
                help_text="Краткая история об утечке (не более 500 символов)",
                max_length=500,
                null=True,
                verbose_name="История",
            ),
        ),
        migrations.AlterField(
            model_name="manageddatabase",
            name="is_encrypted",
            field=models.BooleanField(
                default=False, verbose_name="Зашифрована"
            ),
        ),
    ]
