# Generated by Django 4.2.16 on 2024-12-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0008_alter_manageddatabase_history_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manageddatabase",
            name="history",
            field=models.TextField(
                blank=True,
                default="История об этой базе не найдена",
                help_text="Краткая история об утечке (не более 500 символов)",
                max_length=500,
                null=True,
                verbose_name="История",
            ),
        ),
    ]
