# Generated by Django 4.2.16 on 2024-12-11 18:37

from django.db import migrations, models
import django.db.models.deletion
import search.models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0009_alter_manageddatabase_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manageddatabase",
            name="file",
            field=models.FileField(
                blank=True,
                upload_to=search.models.database_upload_path,
                verbose_name="Файл базы данных",
            ),
        ),
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_index",
                    models.IntegerField(verbose_name="Индекс пользователя"),
                ),
                (
                    "column_name",
                    models.CharField(
                        max_length=255, verbose_name="Название колонки"
                    ),
                ),
                (
                    "value",
                    models.CharField(max_length=255, verbose_name="Значение"),
                ),
                (
                    "database",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data",
                        to="search.manageddatabase",
                        verbose_name="Имя базы данных",
                    ),
                ),
            ],
            options={
                "verbose_name": "Данные",
                "verbose_name_plural": "Данные",
            },
        ),
    ]
