# Generated by Django 4.2.16 on 2024-12-19 22:22

from django.db import migrations, models

import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload a profile picture",
                null=True,
                upload_to="users/images/",
                validators=[users.models.file_size],
                verbose_name="путь к изображению профиля",
            ),
        ),
    ]
