name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  flake8-check:
    name: Flake8 Lint Check
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/pipeline-components/flake8:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Flake8
        run: flake8 --verbose .

  black-check:
    name: Black Code Format Check
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/pipeline-components/black:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Black
        run: black --check .

  django-tests:
    name: Run Django Tests
    needs: [flake8-check, black-check]
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: lambda_search
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
    env:
      DATABASE_URL: postgres://postgres:root@localhost:5432/lambda_search
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: pip install -r requirements/test.txt

      - name: Run Django migrations and tests
        run: |
          cd lambda_search
          python3 manage.py makemigrations
          python3 manage.py migrate
          python3 manage.py test
      

  prod-deploy:
    if: github.ref == 'refs/heads/main'
    needs: [flake8-check, black-check, django-tests]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/lambda_search
          docker compose down
          git reset --hard origin/main  
          git pull origin main
          docker compose --profile prod up --build -d
